version: "3"
services:
  ssr-share:
    # replace username/repo:tag with your name and image details
    image: justcy/ssr-subscription:latest
    restart: always
    ports:
      - 8922:8922
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
