version: "3"
services:
  guanwang:
    # replace username/repo:tag with your name and image details
    image: justcy/go-ssrshare:latest
    restart: always
    networks:
    - code-network
networks:
  code-network:
    driver: bridge